<?php

namespace AppBundle\Repository\Entity;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function paginate($dql, $page = 1, $limit = 10)
    {
        $paginator = new Paginator($dql);
        if (is_numeric($page) && is_numeric($limit)) {
            $paginator->getQuery()
                ->setFirstResult($limit * ($page - 1)) // Offset
                ->setMaxResults($limit); // Limit

            return $paginator;
        } else {
            return null;
        }
    }

    public function getAllPers($currentPage = 1, $limit = 10)
    {
        // Create our query
        $query = $this->createQueryBuilder('p')
            ->getQuery();
            
        $paginator = $this->paginate($query, $currentPage, $limit);

        return array('paginator' => $paginator, 'query' => $query);
    }
}
